a=open("file.txt","a")#adding item
a.write("hello\nmy name is charu")
a.writelines(["i love cooking\n7559298685"])
a.close()
a=open("file.txt","r")
print(a.read())
a.seek(0)
print(a.readline())
a.seek(0)
print(a.readlines())
print(a.readable())
print(a.tell())
a.seekable()
a=open("file.txt","w+")
a.write("i am not feeling well")
a.writable()
a.truncate(5)
a.close
a=open("file.txt","r")
print(a.read())
