a=open("zappcode.txt","w")
a.write("hello all \n my name is charul \n we are learning python \n i love to eat food \n i am 19th")
a.writelines(["\n7559298685"])
a.close()
a=open("zappcode.txt","r+")
a.truncate(15)
a.seek(5)
print(a.tell())
print(a.read())
a.close()